# Python on RStudio

```{r}
library(reticulate)
```

```{r}
conda_create("m-team-machine-learning")
```

##### 找到Rprofile.site的R根目錄{-}

```{r}
site_path = R.home(component = "home")
fname = file.path(site_path, "etc", "Rprofile.site")
file.exists(fname)
```

```{r}
file.edit(fname)
#file.edit("/Library/Frameworks/R.framework/Resources/Rprofile.site")
```

#### 未來開python環境用法{-}

```{r}
library(reticulate)
use_python(Sys.getenv("condaPythonPath"),
           required = T)
use_condaenv("m-team-machine-learning")
```

#### Google API Installation{-}

<https://developers.google.com/api-client-library/python/start/installation> 

```{r}
conda_install(envname = "m-team-machine-learning",
              c("numpy","pandas"))
```

```{r}
conda_install(envname = "m-team-machine-learning",
              "keras")
```


```{r, eval=FALSE}
conda_install(envname="m-team-machine-learning",
              c("google-api-python-client",
                "google-auth-httplib2",
                "google-auth-oauthlib"),
              pip=TRUE)
```


